; Divide every sorcery/incantation's FP cost by this number.
; 2 = half cost, 3 = a third, 1 = no change. Decimals are allowed (e.g. 1.5).
[fp_cost]
divisor = 4
min_cost = 5 ; if the vanilla cost is lower than this value, then the cheaper cost will be used.


[stat_requirements]
divisor = 1
; Divide the stat requirements (Intelligence / Faith / Arcane) of every spell by this number
; 2 = half the required stat, 1 = no change. Decimals allowed.

[debugging]
log_each = 0
debug_console = 0