#include "names.hpp"

#include <cstdio>
#include <unordered_map>

namespace {

// Generated by cmake/embed_names.cmake from Paramdex ER/Names/EquipParamWeapon.txt.
// Defines: const unsigned char kWeaponNamesTxt[]; const size_t kWeaponNamesTxtLen;
#include "weapon_names.inc"

std::unordered_map<int, std::string> g_names;

} // namespace

namespace omni {

void names_init() {
    // Lines of "<id> <name>". UTF-8; a BOM or malformed line is just skipped.
    const char* p   = reinterpret_cast<const char*>(kWeaponNamesTxt);
    const char* end = p + kWeaponNamesTxtLen;
    while (p < end) {
        const char* eol = p;
        while (eol < end && *eol != '\n') ++eol;
        // parse "<digits> <rest>"
        const char* q = p;
        long id = 0;
        bool has_id = false;
        while (q < eol && *q >= '0' && *q <= '9') {
            id = id * 10 + (*q - '0');
            ++q;
            has_id = true;
        }
        if (has_id && q < eol && *q == ' ') {
            ++q;
            const char* e = eol;
            while (e > q && (e[-1] == '\r' || e[-1] == ' ')) --e;
            if (e > q)
                g_names.emplace(static_cast<int>(id), std::string(q, e));
        }
        p = eol + 1;
    }
}

std::string wep_label(int id) {
    char buf[192];
    auto it = g_names.find(id);
    if (it != g_names.end()) {
        std::snprintf(buf, sizeof(buf), "%s (%d)", it->second.c_str(), id);
        return buf;
    }
    // Upgrade rows are base+level (base ids are multiples of 100); Paramdex
    // only names the base row.
    const int level = id % 100;
    it = g_names.find(id - level);
    if (it != g_names.end()) {
        std::snprintf(buf, sizeof(buf), "%s +%d (%d)", it->second.c_str(), level, id);
        return buf;
    }
    std::snprintf(buf, sizeof(buf), "#%d", id);
    return buf;
}

} // namespace omni
