#!/usr/bin/env python3
# ============================================================
#  One-shot generator for CustomTalismanEffects.
#
#  Reads the Paramdex names file (ER/Names/EquipParamAccessory.txt, lines of the
#  form "<id> <name>") and emits:
#
#    ../src/talisman_names.hpp    { id, "name", "effect" } table baked into the DLL
#    ../CustomTalismanEffects.ini default config: every talisman "Name = 0"
#
#  The `effect` string is the hover text shown in the overlay. It is:
#    1. preserved from the CURRENT talisman_names.hpp if already present (so hand
#       edits survive a regen), else
#    2. seeded from the game's own one-line effect text
#       (elden-ring-playground/elden-ring-data -> combined/msg-item.json), else
#    3. left as "" (the 39 DLC talismans -- fill them in talisman_names.hpp).
#
#  => To add/curate an effect, edit the "effect" string directly in
#     src/talisman_names.hpp. Re-running this generator keeps your edits.
#
#  Re-run whenever Paramdex updates its talisman names. Download the names with:
#    curl -L -o EquipParamAccessory.txt \
#      https://raw.githubusercontent.com/soulsmods/Paramdex/master/ER/Names/EquipParamAccessory.txt
#
#  Usage:  python gen_talisman_data.py [EquipParamAccessory.txt]
# ============================================================
import json
import os
import re
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, os.pardir, "src")
ROOT = os.path.join(HERE, os.pardir)
HEADER = os.path.join(SRC, "talisman_names.hpp")
MSG_URL = ("https://raw.githubusercontent.com/elden-ring-playground/"
           "elden-ring-data/main/combined/msg-item.json")


def norm(name):
    # Must match normalize() in main.cpp: lowercase + collapse whitespace.
    return " ".join(name.lower().split())


def cpp_escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def cpp_unescape(s):
    return s.replace('\\"', '"').replace("\\\\", "\\")


def load_names(path):
    rows = []  # (id:int, name:str)
    seen_ids = set()
    seen_names = {}
    with open(path, "r", encoding="utf-8") as f:
        for lineno, raw in enumerate(f, 1):
            line = raw.strip()
            if not line:
                continue
            parts = line.split(" ", 1)
            if len(parts) != 2:
                print(f"  skip line {lineno}: {line!r}")
                continue
            sid, name = parts[0], parts[1].strip()
            try:
                aid = int(sid)
            except ValueError:
                print(f"  skip line {lineno}: bad id {sid!r}")
                continue
            if aid in seen_ids:
                raise SystemExit(f"duplicate accessory id {aid} at line {lineno}")
            key = norm(name)
            if key in seen_names:
                raise SystemExit(
                    f"duplicate normalized name {name!r} (id {aid}) collides with "
                    f"id {seen_names[key]} -- names must be unique to key the .ini")
            seen_ids.add(aid)
            seen_names[key] = aid
            rows.append((aid, name))
    rows.sort(key=lambda r: r[0])
    return rows


# Parse effects already present in the current header so hand edits survive.
_ENTRY_RE = re.compile(
    r'\{\s*(\d+)\s*,\s*"(?:[^"\\]|\\.)*"\s*,\s*"((?:[^"\\]|\\.)*)"\s*\}')


def load_existing_effects(path):
    effects = {}
    if not os.path.exists(path):
        return effects
    with open(path, "r", encoding="utf-8") as f:
        for m in _ENTRY_RE.finditer(f.read()):
            eff = cpp_unescape(m.group(2)).strip()
            if eff:
                effects[int(m.group(1))] = eff
    return effects


# Seed effect text from the game's own item info (base game only; DLC -> blank).
def load_seed_effects():
    try:
        local = os.path.join(HERE, "msg-item.json")
        if os.path.exists(local):
            data = json.load(open(local, encoding="utf-8"))
        else:
            print(f"downloading {MSG_URL} ...")
            with urllib.request.urlopen(MSG_URL, timeout=30) as r:
                data = json.loads(r.read().decode("utf-8"))
        out = {}
        for k, v in data.get("Accessory", {}).items():
            try:
                info = (v.get("info") or "").strip()
                if info:
                    out[int(k)] = info
            except (ValueError, AttributeError):
                pass
        return out
    except Exception as e:  # network optional: existing header effects still win
        print(f"  [warn] could not load seed effects ({e}); leaving unseeded blanks")
        return {}


def write_header(rows, effects):
    lines = [
        "// ============================================================",
        "//  GENERATED by tools/gen_talisman_data.py.",
        "//  ids + names come from Paramdex ER/Names/EquipParamAccessory.txt and",
        "//  should NOT be edited by hand. The \"effect\" hover text, however, MAY be",
        "//  edited here directly -- the generator preserves existing effect strings",
        "//  on re-run (base-game effects are seeded from the game's own text; the",
        "//  DLC ones ship blank for you to fill, e.g. from Fextralife).",
        "// ============================================================",
        "#pragma once",
        "",
        "namespace cte {",
        "",
        "struct TalismanEntry {",
        "    int         id;",
        "    const char* name;",
        "    const char* effect;   // overlay hover text; \"\" if unknown",
        "};",
        "",
        f"// {len(rows)} talismans (base + upgrades + DLC).",
        "static constexpr TalismanEntry kTalismans[] = {",
    ]
    name_w = max(len('"%s",' % cpp_escape(n)) for _, n in rows)
    for aid, name in rows:
        nm = '"%s",' % cpp_escape(name)
        eff = cpp_escape(effects.get(aid, ""))
        lines.append(f'    {{ {str(aid).ljust(4)}, {nm.ljust(name_w)} "{eff}" }},')
    lines += [
        "};",
        "",
        "static constexpr int kTalismanCount =",
        "    static_cast<int>(sizeof(kTalismans) / sizeof(kTalismans[0]));",
        "",
        "} // namespace cte",
        "",
    ]
    with open(HEADER, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    filled = sum(1 for a, _ in rows if effects.get(a))
    print(f"wrote {HEADER} ({len(rows)} entries, {filled} with effect text)")


def write_ini(rows):
    out = os.path.join(ROOT, "CustomTalismanEffects.ini")
    width = max(len(name) for _, name in rows)
    lines = [
        "; ============================================================",
        ";  CustomTalismanEffects",
        ";",
        ";  Set a talisman to 1 to apply its effects to your character",
        ";  passively -- as if it were equipped, but WITHOUT using a",
        ";  talisman slot or occupying inventory. 0 = off.",
        ";",
        ";  Upgraded versions (+1/+2/+3) and DLC talismans are listed as",
        ";  their own separate lines. Names come from Paramdex; do not",
        ";  rename them. You can also toggle these live in-game with the",
        ";  overlay (default: Insert, or L3+R3). OFFLINE USE ONLY (EAC).",
        ";",
        ";  Talismans added by other mods (Reforged, The Convergence, ...) are",
        ";  detected automatically -- they appear under the overlay's \"Mod-Added\"",
        ";  tab and are written here the first time you enable one and save.",
        "; ============================================================",
        "",
        "[overlay]",
        "toggle_key           = Insert   ; key to open/close the in-game panel",
        "toggle_gamepad_combo = L3+R3    ; controller combo to open/close (buttons joined with +)",
        ";   Available buttons: A B X Y  LB RB  L3 R3  Start Back  Up Down Left Right",
        ";   Examples: L3+R3   LB+RB   Back+Start   Y+R3",
        "allow_stacking       = 0        ; 1 = ignore talisman families (stack anything)",
        "",
        "[talismans]",
    ]
    for aid, name in rows:
        lines.append(f"{name.ljust(width)} = 0")
    lines += [
        "",
        "[debugging]",
        "log_each      = 1   ; log each SpEffect applied / removed",
        "debug_console = 0   ; 1 opens a console window with live logs",
        "",
    ]
    with open(out, "w", encoding="utf-8", newline="\r\n") as f:
        f.write("\n".join(lines))
    print(f"wrote {out} ({len(rows)} talismans)")


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "EquipParamAccessory.txt")
    if not os.path.exists(src):
        raise SystemExit(f"names file not found: {src}")
    rows = load_names(src)

    # effect precedence: existing header edit > game seed > blank
    effects = load_seed_effects()
    effects.update(load_existing_effects(HEADER))  # hand edits win

    write_header(rows, effects)
    write_ini(rows)
    print("done.")


if __name__ == "__main__":
    main()
